# Generated by Django 5.1.7 on 2025-03-23 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ShortURL',
            fields=[
                ('alias', models.CharField(max_length=48, primary_key=True, serialize=False)),
                ('long_url', models.URLField(db_index=True, max_length=2048)),
            ],
        ),
    ]
